In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Data.csv")
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [3]:
X=df.drop("Purchased",axis=1) #veya df.iloc[:,:-1].values
y=df["Purchased"] # veya df.iloc[:,-1].values

In [4]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [5]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

## Taking care of missing data

* saysıal kolonlarda eksik değerleri kendi sütununun ortalamaları ile doldurdum.Yani age kolonunu yaşların ortalaması, salary kolonununda ki eksik değerleri maaşların ortalaması ile doldurdum.

In [6]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(X.iloc[:,1:3])
X.iloc[:,1:3]=imputer.transform(X.iloc[:,1:3])

#veya
#imputer.fit(X[["Age","Salary"]])
#X[["Age","Salary"]]=imputer.transform(X[["Age","Salary"]])



In [7]:
X

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

## Encoding categorical data

In [9]:
#başka bir yöntem: sonuc 1,0 diye ayırabilecegimiz bir prblem ise bunun sonuca olan etkisini ortalamaları kaç 

#avgs=dict(df.groupby("Country").mean()["Salary"])
#df["Country"] = df["Country"].apply(lambda x : avgs[x])
#df["Country"]


In [10]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

## Encoding the Independent (bagımsız) Variable

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])], remainder = "passthrough")
# passthrough: uygulanmayacak sütunları tutmak istediğimizi söyleyen kod.
X = ct.fit_transform(X)

## Encoding the Dependent  (bagımlı) Variable

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [21]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
# Not: Veri setinin eğitim ve test setine bölüdkten sonra özellik ölçeklendirmesi uygulanır.

In [24]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)


In [31]:
print(X_train)

[[0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 4.00000000e+01 6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 4.40000000e+01 7.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 3.80000000e+01 6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 4.80000000e+01 7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 5.00000000e+01 8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 3.50000000e+01 5.80000000e+04]]


In [26]:
print(X_test)

[[0.0e+00 1.0e+00 0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [1.0e+00 0.0e+00 1.0e+00 0.0e+00 0.0e+00 3.7e+01 6.7e+04]]


In [27]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [28]:
print(y_test)

[0 1]


## Feature Scaling

In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:, 3:])

In [39]:
print(X_train)

[[ 0.          1.          0.         -0.57735027  1.29099445 -0.19159184
  -1.07812594]
 [ 0.          1.          0.          1.73205081 -0.77459667 -0.01411729
  -0.07013168]
 [ 1.          0.          1.         -0.57735027 -0.77459667  0.56670851
   0.63356243]
 [ 0.          1.          0.         -0.57735027  1.29099445 -0.30453019
  -0.30786617]
 [ 0.          1.          0.         -0.57735027  1.29099445 -1.90180114
  -1.42046362]
 [ 1.          0.          1.         -0.57735027 -0.77459667  1.14753431
   1.23265336]
 [ 0.          1.          0.          1.73205081 -0.77459667  1.43794721
   1.57499104]
 [ 1.          0.          1.         -0.57735027 -0.77459667 -0.74014954
  -0.56461943]]


In [40]:
print(X_test)

[[0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  2.77555756e-17 3.00000000e+01 5.40000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 8.32667268e-17
  2.77555756e-17 3.70000000e+01 6.70000000e+04]]


## Sınıflandırma problemleri için paketler

* pip install xgboost
* pip yükleme lightgbm
* pip install catboost

* import numpy as np
* import pandas as pd 
* import statsmodels.api as sm
* import statsmodels.formula.api as smf
* import seaborn as sns
* from sklearn.preprocessing import scale 
* from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
* from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
* from sklearn.metrics import recall_score,precision_score,f1_score
* from sklearn.metrics import roc_auc_score,roc_curve
* import statsmodels.formula.api as smf
* import matplotlib.pyplot as plt
* from sklearn.neighbors import KNeighborsClassifier
* from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
* from sklearn.linear_model import LogisticRegression
* from sklearn.svm import SVC
* from sklearn.naive_bayes import GaussianNB
* from sklearn import tree
* from sklearn.ensemble import RandomForestClassifier
* from sklearn.ensemble import GradientBoostingClassifier
* from xgboost import XGBClassifier
* #from lightgbm import LGBMClassifier
* from catboost import CatBoostClassifier

* from warnings import filterwarnings
* filterwarnings('ignore')